[package]
name = "dummy"
version = "0.1.0"
description = "Example Zabbix loadable module written in Rust"
authors = ["Marin Atanasov Nikolov <dnaeon@gmail.com>"]

[lib]
name = "rust_dummy"
crate-type = ["dylib"]

[dependencies.rand]
version = "*"

[dependencies.zbx]
path = "../.."
# git = "https://github.com/NSenaud/rust-zbx.git"
# branch = "upgrade-to-rust-1.22"

